version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: gunicorn server:app --bind 0.0.0.0:5000 -w 4 -k uvicorn.workers.UvicornWorker
    networks:
      - web
    env_file:
      - .env.prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
      - "traefik.http.routers.fastapi.rule=Host(`pypi.shorten.ru.com`)"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=lets-encrypt"

  db:
      image: postgres
      ports:
        - "5432:5432"
      networks:
        - web
      env_file:
        - .env.prod
      volumes:
        - postgres_data_pypi:/var/lib/postgresql/data/

volumes:
  postgres_data_pypi:

networks:
  web:
    external: true
