version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "gunicorn server:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080"
    networks:
      - web
    env_file:
      - .env.prod
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=8080
      - traefik.http.routers.app.rule=Host(`pypi.shorten.ru.com`)
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=lets-encrypt

  db:
      image: postgres
      ports:
        - "5432:5432"
      networks:
        - web
      env_file:
        - .env.prod
      volumes:
        - postgres_data_pypi:/var/lib/postgresql/data/

volumes:
  postgres_data_pypi:

networks:
  web:
    external: true
