[tool.poetry]
name = "async-pypi-app"
version = "0.1.0"
description = ""
authors = ["Denis Novikov <alpden550@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "uvicorn"
uvicorn = "^0.15.0"

[tool.poetry.dev-dependencies]
black = "wemake-python-styleguide"
wemake-python-styleguide = "^0.15.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
