"""add_maintainers

Revision ID: d0c76512b037
Revises: a03a10f4e0d8
Create Date: 2021-12-25 11:17:10.940407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c76512b037'
down_revision = 'a03a10f4e0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('maintainers', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'maintainers')
    # ### end Alembic commands ###
