"""empty message

Revision ID: 62deba1fd8ac
Revises: 
Create Date: 2021-12-24 07:52:40.854746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "62deba1fd8ac"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_login", sa.DateTime(), nullable=True))
    op.drop_index("ix_users_last_login_at", table_name="users")
    op.create_index(op.f("ix_users_last_login"), "users", ["last_login"], unique=False)
    op.drop_column("users", "last_login_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_login_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_users_last_login"), table_name="users")
    op.create_index("ix_users_last_login_at", "users", ["last_login_at"], unique=False)
    op.drop_column("users", "last_login")
    # ### end Alembic commands ###
