"""empty message

Revision ID: ee74001b3602
Revises: 1de0b8ed8534
Create Date: 2021-12-24 08:02:21.617588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee74001b3602'
down_revision = '1de0b8ed8534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'packages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'packages', type_='foreignkey')
    op.drop_column('packages', 'user_id')
    # ### end Alembic commands ###
